In [1]:
import pandas as pd 

df = pd.read_csv("../data/Crop_recommendation.csv")
df

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [2]:
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [3]:
df.tail()

        N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [4]:
df.shape

(2200, 8)

In [5]:
df.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [7]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [8]:
df.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [10]:
df.groupby("label")["rainfall"].describe()

,count,mean,std,min,25%,50%,75%,max
label,,,,,,,,
apple,100.0,112.654779,7.102985,100.117344,106.070135,112.979230,118.449546,124.983162
banana,100.0,104.626980,9.398150,90.109781,96.471109,105.007750,112.092171,119.847970
blackgram,100.0,67.884151,4.184186,60.417903,64.049755,68.293539,71.397924,74.915595
chickpea,100.0,80.058977,7.944350,65.113656,73.610409,79.692282,85.824482,94.781896
coconut,100.0,175.686646,29.472333,131.090008,149.126478,171.999922,202.351490,225.632366
coffee,100.0,158.066295,25.695086,115.156401,136.011746,157.770963,181.472018,199.473564
cotton,100.0,80.398043,11.231812,60.653817,70.894298,80.237095,90.418270,99.931008
grapes,100.0,69.611829,2.951759,65.010953,66.836826,69.536186,71.609366,74.915062
jute,100.0,174.792798,15.078367,150.235524,161.090683,175.590814,187.641532,199.836291
kidneybeans,100.0,105.919778,26.111384,60.275525,85.824741,107.399392,129.399964,149.744103
lentil,100.0,45.680454,5.632972,35.034848,41.571821,46.553255,49.997992,54.939377
maize,100.0,84.766988,15.547339,60.651715,70.384556,83.471553,99.877090,109.751538
mango,100.0,94.704515,3.338577,89.291476,91.612674,94.905973,97.475774,100.812466
mothbeans,100.0,51.198487,13.750693,30.920140,37.985391,51.182738,64.185059,74.443307
mungbean,100.0,48.403601,7.117214,36.120429,43.103300,49.028171,54.837313,59.872321
muskmelon,100.0,24.689952,2.773999,20.211267,22.067976,24.721512,26.861601,29.866814
orange,100.0,110.474969,5.717125,100.173796,106.220011,110.684073,115.565866,119.694658
papaya,100.0,142.627839,64.396577,40.351531,81.940962,139.000698,202.394057,248.859299
pigeonpeas,100.0,149.457564,32.986321,90.054227,122.345984,154.310507,177.907288,198.829881
pomegranate,100.0,107.528442,2.895339,102.518476,104.967353,107.588201,109.958146,112.475094
rice,100.0,236.181114,34.291825,182.561632,204.334023,233.119859,264.126903,298.560117
watermelon,100.0,50.786219,5.867006,40.126504,46.063351,50.671903,56.412795,59.759800

In [12]:
print(df["rainfall"].describe())
print(df.groupby("label")["rainfall"].mean().sort_values())

count    2200.000000
mean      103.463655
std        54.958389
min        20.211267
25%        64.551686
50%        94.867624
75%       124.267508
max       298.560117
Name: rainfall, dtype: float64
label
muskmelon       24.689952
lentil          45.680454
mungbean        48.403601
watermelon      50.786219
mothbeans       51.198487
blackgram       67.884151
grapes          69.611829
chickpea        80.058977
cotton          80.398043
maize           84.766988
mango           94.704515
banana         104.626980
kidneybeans    105.919778
pomegranate    107.528442
orange         110.474969
apple          112.654779
papaya         142.627839
pigeonpeas     149.457564
coffee         158.066295
jute           174.792798
coconut        175.686646
rice           236.181114
Name: rainfall, dtype: float64